// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:lucky_wheel_clean_architecture/features/history/domain/models/history_item_model.dart';
import 'package:lucky_wheel_clean_architecture/features/presets/domain/models/preset_model.dart';
import 'package:lucky_wheel_clean_architecture/features/presets/domain/models/slice_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HistoryItemAdapter());
    registerAdapter(PresetAdapter());
    registerAdapter(SliceAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HistoryItemAdapter());
    registerAdapter(PresetAdapter());
    registerAdapter(SliceAdapter());
  }
}
